/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AvonButton {
        "color"?: 'primary' |'secondary' |'clear' |'light';
        "disabled"?: boolean;
        /**
          * Button Label
         */
        "label": string;
        "shape"?: 'full' |'round'|'smooth';
        "size"?: 'large' | 'medium' | 'small';
        "width"?: 'fullwidth' | 'mediumwidth' | 'smallwidth';
    }
    interface AvonHeading {
        /**
          * The first name
         */
        "label": string;
        "level"?: 'h1' | 'h2' | 'h3';
    }
    interface AvonLink {
        /**
          * color
         */
        "color": string;
        /**
          * font-family
         */
        "fontfamily": string;
        /**
          * font-size
         */
        "fontsize": string;
        /**
          * font-weight
         */
        "fontweight": string;
        /**
          * Label
         */
        "label": string;
        /**
          * link
         */
        "link": string;
        /**
          * text-decoration
         */
        "textdecoration": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SwcBox_container {
        /**
          * background-color
         */
        "backgroundcolor": string;
        /**
          * height
         */
        "height": string;
        /**
          * Width
         */
        "width": string;
    }
    interface SwcLabel {
        /**
          * color
         */
        "color": string;
        /**
          * font-family
         */
        "fontfamily": string;
        /**
          * font-size
         */
        "fontsize": string;
        /**
          * font-weight
         */
        "fontweight": string;
        /**
          * Label
         */
        "label": string;
    }
}
declare global {
    interface HTMLAvonButtonElement extends Components.AvonButton, HTMLStencilElement {
    }
    var HTMLAvonButtonElement: {
        prototype: HTMLAvonButtonElement;
        new (): HTMLAvonButtonElement;
    };
    interface HTMLAvonHeadingElement extends Components.AvonHeading, HTMLStencilElement {
    }
    var HTMLAvonHeadingElement: {
        prototype: HTMLAvonHeadingElement;
        new (): HTMLAvonHeadingElement;
    };
    interface HTMLAvonLinkElement extends Components.AvonLink, HTMLStencilElement {
    }
    var HTMLAvonLinkElement: {
        prototype: HTMLAvonLinkElement;
        new (): HTMLAvonLinkElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSwcBox_containerElement extends Components.SwcBox_container, HTMLStencilElement {
    }
    var HTMLSwcBox_containerElement: {
        prototype: HTMLSwcBox_containerElement;
        new (): HTMLSwcBox_containerElement;
    };
    interface HTMLSwcLabelElement extends Components.SwcLabel, HTMLStencilElement {
    }
    var HTMLSwcLabelElement: {
        prototype: HTMLSwcLabelElement;
        new (): HTMLSwcLabelElement;
    };
    interface HTMLElementTagNameMap {
        "avon-button": HTMLAvonButtonElement;
        "avon-heading": HTMLAvonHeadingElement;
        "avon-link": HTMLAvonLinkElement;
        "my-component": HTMLMyComponentElement;
        "swc-box_container": HTMLSwcBox_containerElement;
        "swc-label": HTMLSwcLabelElement;
    }
}
declare namespace LocalJSX {
    interface AvonButton {
        "color"?: 'primary' |'secondary' |'clear' |'light';
        "disabled"?: boolean;
        /**
          * Button Label
         */
        "label"?: string;
        "shape"?: 'full' |'round'|'smooth';
        "size"?: 'large' | 'medium' | 'small';
        "width"?: 'fullwidth' | 'mediumwidth' | 'smallwidth';
    }
    interface AvonHeading {
        /**
          * The first name
         */
        "label"?: string;
        "level"?: 'h1' | 'h2' | 'h3';
    }
    interface AvonLink {
        /**
          * color
         */
        "color"?: string;
        /**
          * font-family
         */
        "fontfamily"?: string;
        /**
          * font-size
         */
        "fontsize"?: string;
        /**
          * font-weight
         */
        "fontweight"?: string;
        /**
          * Label
         */
        "label"?: string;
        /**
          * link
         */
        "link"?: string;
        /**
          * text-decoration
         */
        "textdecoration"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SwcBox_container {
        /**
          * background-color
         */
        "backgroundcolor"?: string;
        /**
          * height
         */
        "height"?: string;
        /**
          * Width
         */
        "width"?: string;
    }
    interface SwcLabel {
        /**
          * color
         */
        "color"?: string;
        /**
          * font-family
         */
        "fontfamily"?: string;
        /**
          * font-size
         */
        "fontsize"?: string;
        /**
          * font-weight
         */
        "fontweight"?: string;
        /**
          * Label
         */
        "label"?: string;
    }
    interface IntrinsicElements {
        "avon-button": AvonButton;
        "avon-heading": AvonHeading;
        "avon-link": AvonLink;
        "my-component": MyComponent;
        "swc-box_container": SwcBox_container;
        "swc-label": SwcLabel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "avon-button": LocalJSX.AvonButton & JSXBase.HTMLAttributes<HTMLAvonButtonElement>;
            "avon-heading": LocalJSX.AvonHeading & JSXBase.HTMLAttributes<HTMLAvonHeadingElement>;
            "avon-link": LocalJSX.AvonLink & JSXBase.HTMLAttributes<HTMLAvonLinkElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "swc-box_container": LocalJSX.SwcBox_container & JSXBase.HTMLAttributes<HTMLSwcBox_containerElement>;
            "swc-label": LocalJSX.SwcLabel & JSXBase.HTMLAttributes<HTMLSwcLabelElement>;
        }
    }
}
