/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AvonButton {
        "color"?: 'primary' |'secondary' |'clear' |'light';
        "disabled"?: boolean;
        /**
          * Button Label
         */
        "label": string;
        "shape"?: 'full' |'round'|'smooth';
        "size"?: 'large' | 'medium' | 'small';
        "width"?: 'fullwidth' | 'mediumwidth' | 'smallwidth';
    }
    interface AvonHeading {
        /**
          * The first name
         */
        "label": string;
        "level"?: 'h1' | 'h2' | 'h3';
    }
    interface AvonLink {
        /**
          * color
         */
        "color": string;
        /**
          * font-family
         */
        "fontfamily": string;
        /**
          * font-size
         */
        "fontsize": string;
        /**
          * font-weight
         */
        "fontweight": string;
        /**
          * link
         */
        "link": string;
        /**
          * text-decoration
         */
        "textdecoration": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SwcBox_container {
        /**
          * background-color
         */
        "backgroundcolor": string;
        /**
          * height
         */
        "height": string;
        /**
          * Width
         */
        "width": string;
    }
    interface SwcImg {
        /**
          * alt
         */
        "alt": string;
        /**
          * height
         */
        "height": string;
        /**
          * src
         */
        "src": string;
        /**
          * width
         */
        "width": string;
    }
    interface SwcLabel {
        /**
          * color
         */
        "color": string;
        /**
          * font-family
         */
        "fontfamily": string;
        /**
          * font-size
         */
        "fontsize": string;
        /**
          * font-weight
         */
        "fontweight": string;
        /**
          * Label
         */
        "label": string;
    }
    interface SwcModal {
        /**
          * Button color
         */
        "btncolor"?: 'primary' |'secondary' |'clear' |'light';
        /**
          * button-label
         */
        "buttonlabel": string;
        /**
          * height
         */
        "height": string;
        /**
          * Heading
         */
        "modaltitle": string;
        /**
          * open
         */
        "open": boolean;
        /**
          * Position of modal
         */
        "position"?: 'center' | 'left' | 'right' |'top'|'bottom';
        /**
          * Title color
         */
        "titlecolor": string;
        /**
          * Title font-family
         */
        "titlefontfamily": string;
        /**
          * Title font-size
         */
        "titlefontsize": string;
        /**
          * Title font-weight
         */
        "titlefontweight": string;
        /**
          * width
         */
        "width": string;
    }
    interface SwcTextbox {
        "disabled"?: boolean;
        "placeholder"?: string;
        "shape"?: 'full' |'round'|'smooth';
        "usecase"?: 'search' |'loginform';
        "width"?: 'fullwidth' | 'mediumwidth' | 'smallwidth';
    }
}
declare global {
    interface HTMLAvonButtonElement extends Components.AvonButton, HTMLStencilElement {
    }
    var HTMLAvonButtonElement: {
        prototype: HTMLAvonButtonElement;
        new (): HTMLAvonButtonElement;
    };
    interface HTMLAvonHeadingElement extends Components.AvonHeading, HTMLStencilElement {
    }
    var HTMLAvonHeadingElement: {
        prototype: HTMLAvonHeadingElement;
        new (): HTMLAvonHeadingElement;
    };
    interface HTMLAvonLinkElement extends Components.AvonLink, HTMLStencilElement {
    }
    var HTMLAvonLinkElement: {
        prototype: HTMLAvonLinkElement;
        new (): HTMLAvonLinkElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSwcBox_containerElement extends Components.SwcBox_container, HTMLStencilElement {
    }
    var HTMLSwcBox_containerElement: {
        prototype: HTMLSwcBox_containerElement;
        new (): HTMLSwcBox_containerElement;
    };
    interface HTMLSwcImgElement extends Components.SwcImg, HTMLStencilElement {
    }
    var HTMLSwcImgElement: {
        prototype: HTMLSwcImgElement;
        new (): HTMLSwcImgElement;
    };
    interface HTMLSwcLabelElement extends Components.SwcLabel, HTMLStencilElement {
    }
    var HTMLSwcLabelElement: {
        prototype: HTMLSwcLabelElement;
        new (): HTMLSwcLabelElement;
    };
    interface HTMLSwcModalElement extends Components.SwcModal, HTMLStencilElement {
    }
    var HTMLSwcModalElement: {
        prototype: HTMLSwcModalElement;
        new (): HTMLSwcModalElement;
    };
    interface HTMLSwcTextboxElement extends Components.SwcTextbox, HTMLStencilElement {
    }
    var HTMLSwcTextboxElement: {
        prototype: HTMLSwcTextboxElement;
        new (): HTMLSwcTextboxElement;
    };
    interface HTMLElementTagNameMap {
        "avon-button": HTMLAvonButtonElement;
        "avon-heading": HTMLAvonHeadingElement;
        "avon-link": HTMLAvonLinkElement;
        "my-component": HTMLMyComponentElement;
        "swc-box_container": HTMLSwcBox_containerElement;
        "swc-img": HTMLSwcImgElement;
        "swc-label": HTMLSwcLabelElement;
        "swc-modal": HTMLSwcModalElement;
        "swc-textbox": HTMLSwcTextboxElement;
    }
}
declare namespace LocalJSX {
    interface AvonButton {
        "color"?: 'primary' |'secondary' |'clear' |'light';
        "disabled"?: boolean;
        /**
          * Button Label
         */
        "label"?: string;
        "shape"?: 'full' |'round'|'smooth';
        "size"?: 'large' | 'medium' | 'small';
        "width"?: 'fullwidth' | 'mediumwidth' | 'smallwidth';
    }
    interface AvonHeading {
        /**
          * The first name
         */
        "label"?: string;
        "level"?: 'h1' | 'h2' | 'h3';
    }
    interface AvonLink {
        /**
          * color
         */
        "color"?: string;
        /**
          * font-family
         */
        "fontfamily"?: string;
        /**
          * font-size
         */
        "fontsize"?: string;
        /**
          * font-weight
         */
        "fontweight"?: string;
        /**
          * link
         */
        "link"?: string;
        /**
          * text-decoration
         */
        "textdecoration"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SwcBox_container {
        /**
          * background-color
         */
        "backgroundcolor"?: string;
        /**
          * height
         */
        "height"?: string;
        /**
          * Width
         */
        "width"?: string;
    }
    interface SwcImg {
        /**
          * alt
         */
        "alt"?: string;
        /**
          * height
         */
        "height"?: string;
        /**
          * src
         */
        "src"?: string;
        /**
          * width
         */
        "width"?: string;
    }
    interface SwcLabel {
        /**
          * color
         */
        "color"?: string;
        /**
          * font-family
         */
        "fontfamily"?: string;
        /**
          * font-size
         */
        "fontsize"?: string;
        /**
          * font-weight
         */
        "fontweight"?: string;
        /**
          * Label
         */
        "label"?: string;
    }
    interface SwcModal {
        /**
          * Button color
         */
        "btncolor"?: 'primary' |'secondary' |'clear' |'light';
        /**
          * button-label
         */
        "buttonlabel"?: string;
        /**
          * height
         */
        "height"?: string;
        /**
          * Heading
         */
        "modaltitle"?: string;
        "onBtnClick"?: (event: CustomEvent<any>) => void;
        /**
          * open
         */
        "open"?: boolean;
        /**
          * Position of modal
         */
        "position"?: 'center' | 'left' | 'right' |'top'|'bottom';
        /**
          * Title color
         */
        "titlecolor"?: string;
        /**
          * Title font-family
         */
        "titlefontfamily"?: string;
        /**
          * Title font-size
         */
        "titlefontsize"?: string;
        /**
          * Title font-weight
         */
        "titlefontweight"?: string;
        /**
          * width
         */
        "width"?: string;
    }
    interface SwcTextbox {
        "disabled"?: boolean;
        "placeholder"?: string;
        "shape"?: 'full' |'round'|'smooth';
        "usecase"?: 'search' |'loginform';
        "width"?: 'fullwidth' | 'mediumwidth' | 'smallwidth';
    }
    interface IntrinsicElements {
        "avon-button": AvonButton;
        "avon-heading": AvonHeading;
        "avon-link": AvonLink;
        "my-component": MyComponent;
        "swc-box_container": SwcBox_container;
        "swc-img": SwcImg;
        "swc-label": SwcLabel;
        "swc-modal": SwcModal;
        "swc-textbox": SwcTextbox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "avon-button": LocalJSX.AvonButton & JSXBase.HTMLAttributes<HTMLAvonButtonElement>;
            "avon-heading": LocalJSX.AvonHeading & JSXBase.HTMLAttributes<HTMLAvonHeadingElement>;
            "avon-link": LocalJSX.AvonLink & JSXBase.HTMLAttributes<HTMLAvonLinkElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "swc-box_container": LocalJSX.SwcBox_container & JSXBase.HTMLAttributes<HTMLSwcBox_containerElement>;
            "swc-img": LocalJSX.SwcImg & JSXBase.HTMLAttributes<HTMLSwcImgElement>;
            "swc-label": LocalJSX.SwcLabel & JSXBase.HTMLAttributes<HTMLSwcLabelElement>;
            "swc-modal": LocalJSX.SwcModal & JSXBase.HTMLAttributes<HTMLSwcModalElement>;
            "swc-textbox": LocalJSX.SwcTextbox & JSXBase.HTMLAttributes<HTMLSwcTextboxElement>;
        }
    }
}
