/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AvonButton {
        "color"?: 'primary' |'secondary';
        "disabled"?: boolean;
        /**
          * Button Label
         */
        "label": string;
        "shape"?: 'full' |'round'|'smooth';
        "size"?: 'large' | 'medium' | 'small';
        "width"?: 'fullwidth' | 'mediumwidth' | 'smallwidth';
    }
    interface AvonHeading {
        /**
          * The first name
         */
        "label": string;
        "level"?: 'h1' | 'h2' | 'h3';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLAvonButtonElement extends Components.AvonButton, HTMLStencilElement {
    }
    var HTMLAvonButtonElement: {
        prototype: HTMLAvonButtonElement;
        new (): HTMLAvonButtonElement;
    };
    interface HTMLAvonHeadingElement extends Components.AvonHeading, HTMLStencilElement {
    }
    var HTMLAvonHeadingElement: {
        prototype: HTMLAvonHeadingElement;
        new (): HTMLAvonHeadingElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "avon-button": HTMLAvonButtonElement;
        "avon-heading": HTMLAvonHeadingElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AvonButton {
        "color"?: 'primary' |'secondary';
        "disabled"?: boolean;
        /**
          * Button Label
         */
        "label"?: string;
        "shape"?: 'full' |'round'|'smooth';
        "size"?: 'large' | 'medium' | 'small';
        "width"?: 'fullwidth' | 'mediumwidth' | 'smallwidth';
    }
    interface AvonHeading {
        /**
          * The first name
         */
        "label"?: string;
        "level"?: 'h1' | 'h2' | 'h3';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "avon-button": AvonButton;
        "avon-heading": AvonHeading;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "avon-button": LocalJSX.AvonButton & JSXBase.HTMLAttributes<HTMLAvonButtonElement>;
            "avon-heading": LocalJSX.AvonHeading & JSXBase.HTMLAttributes<HTMLAvonHeadingElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
